services:
  - type: web
    name: unicity-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Unicity
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:blDI2fwpE0/Lx+VPvMTusc70WXGLIrgu752n+LYON04=
      - key: APP_URL
        value: https://unicity-app.onrender.com
      - key: ASSET_URL
        value: https://unicity-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        value: postgresql://neondb_owner:npg_M2HNogVU8sKd@ep-young-waterfall-ab0e4v7m-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: APP_LOCALE
        value: fr
